GET http://localhost:8080/payment/8498714638
Action: INQUIRY
Content-Type: application/json
Authorization: Bearer YWRtaW4=

{
    "billing" : "081316006010"
}

### 
POST http://localhost:8080/payment/8498714638
Action: PAYMENT
Content-Type: application/json
Authorization: Bearer YWRtaW4=

{
    "account" : "1154711190",
    "amount": 10
}

###
GET http://localhost:8080/purchase/8498714638
Action: INQUIRY
Content-Type: application/json
Authorization: Bearer YWRtaW4=

{
    "billing" : "081316006010"
}

### 
POST http://localhost:8080/purchase/8498714638
Action: PAYMENT
Content-Type: application/json
Authorization: Bearer YWRtaW4=

{
    "account" : "1154711190",
    "amount": 10
}